### ISSUE TITLE
Booking  enhancements

### ISSUE THREAD

**Issue by Petitoto** [aeecleclair/Titan#115]
Some features have been requested by Centraliens:

- [x] #141
- [x] improves the visibility of accepted / rejected bookings
- [x] #138
- [x] #139
- [x] #140

**Comment by Flavio0834** [comment]
Some more enhancements that we discussed today :

- [ ] The note shouldn't be mandatory
- [ ] Show applicant's name on reservation's details (GET endpoint "/bdebooking/bookings/{booking_id}/applicant" exists, and getting booking by id as it is already used certainly also gives the applicant's user id)
- [ ] Show entity ("Pour qui?") on each reservation on the calendar or on reservation's details
- [ ] It should be possible to remove a room (the endpoint exists, and it is needed because "Barbecue" should be removed)

**Comment by julien4215** [comment]
> * [ ]  allow Booking managers to accept or reject a booking that is already started

It is already possible for managers to accept or reject a booking that is already started but not ended.
Should it still be possible to accept or reject  a booking that has ended ?

**Comment by armanddidierjean** [comment]
- [ ] add the creation date in `Booking` objects
 - [ ] sort bookings by creation date instead of reservation date

**Comment by Petitoto** [comment]
- [ ] Allow admins to confirm past reservations

**Comment by julien4215** [comment]
Solved by #185
