### ISSUE TITLE
Booking calendar is too small

### ISSUE THREAD

**Issue by Petitoto** [aeecleclair/Titan#182]
Calendar in the booking module is too small on some devices and on the web.

We could increase its height (to near the full page size) by allowing scrolling to view our reservation cards under the calendar.

**Comment by maximeroucher** [comment]
Please provide an image, since it depend on the screen size

**Comment by Petitoto** [comment]
> Please provide an image, since it depend on the screen size

![image](https://github.com/aeecleclair/Titan/assets/27863028/2e9e11f5-a5b0-4c4b-a679-29d69ccd5f3f)

**Comment by Petitoto** [comment]
Could be included in #176 as this is a minor ui change
@julien4215

**Comment by julien4215** [comment]
The solution for this issue is not satisfying as it gives a fixed size to the calendar. The calendar should be able to expand if there is space available while having a minimum height of 400.

![Screenshot from 2023-11-20 13-28-56](https://github.com/aeecleclair/Titan/assets/120588494/acf0be09-5ded-48f9-8a8e-f5892615e312)

**Comment by julien4215** [comment]
Solved in #185
